# This is a basic workflow to help you get started with Actions

name: diff-settings
on: push

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wayofthepie/gram-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          diff: true
